#!/usr/bin/env python
import os
import sys

DNS_NODE = 'p5-dns.5700.network'
HTTP_NODES = {'p5-http-a.5700.network'}
BUILD_SERVER = 'cs5700cdnproject.ccs.neu.edu'
ORIGIN_SERVER = 'cs5700cdnorigin.ccs.neu.edu'

def parse_args(args_list):
    print(args_list)
    port, origin_server, name, username, keyfile = None, None, None, None, None
    
    for i in range(len(args_list)):
        #print(args_list[i], args_list[i+1])
        if args_list[i] == '-p':
            port = args_list[i+1]
        elif args_list[i] == '-o':
            origin_server = args_list[i+1]
        elif args_list[i] == '-n':
            name = args_list[i+1]
        elif args_list[i] == '-u':
            username = args_list[i+1]
        elif args_list[i] == '-i':
            keyfile = args_list[i+1]
    
    return port, origin_server, name, username, keyfile

def run_dns(port, name, username, keyfile):
    # Run dnsserver on dns node
    run_command = f'ssh -i {keyfile} {username}@{DNS_NODE} ./dnsserver -p {port} -n {name}'
    os.system(run_command)
    

def run_http(port, origin, username, keyfile):
    # Run httpserver on each replica server
    for node in HTTP_NODES:
        ssh_command = f'ssh -i {keyfile} {username}@{node} ./httpserver -p {port} -o {origin}'
        os.system(ssh_command)

def main():
    port, origin_server, name, username, keyfile = parse_args(sys.argv[1:])
    print(port, origin_server, name, username, keyfile)
    
    run_dns(port, name, username, keyfile)
    run_http(port, origin_server, username, keyfile)

main()