#!/usr/bin/env python
import os
import sys

KEY = "~/.ssh/id_ed25519.pub"
DNS_NODE = "p5-dns.5700.network"
HTTP_NODES = ["p5-http-a.5700.network", "p5-http-b.5700.network", "p5-http-c.5700.network",
                "p5-http-d.5700.network", "p5-http-e.5700.network", "p5-http-f.5700.network", "p5-http-g.5700.network"]
BUILD_SERVER = "cs5700cdnproject.ccs.neu.edu"
ORIGIN_SERVER = "cs5700cdnorigin.ccs.neu.edu"
# ./[deploy|run|stop]CDN -p <port> -o <origin> -n <name> -u <username> -i <keyfile>

#./stopCDN -p 40015 -o cs5700cdnorigin.ccs.neu.edu -n team_t -u team_t -i ~/.ssh/id_ed25519.pub

def parse_args(args_list):
    print(args_list)
    port, origin_server, name, username, keyfile = None, None, None, None, None

    for i in range(len(args_list)):
        if args_list[i] == "-p":
            port = args_list[i + 1]
        elif args_list[i] == "-o":
            origin_server = args_list[i + 1]
        elif args_list[i] == "-n":
            name = args_list[i + 1]
        elif args_list[i] == "-u":
            username = args_list[i + 1]
        elif args_list[i] == "-i":
            keyfile = args_list[i + 1]

    return port, origin_server, name, username, keyfile


def stop_dns(username, keyfile):
    ssh_command = (
        "ssh -i "
        + keyfile
        + " "
        + username
        + "@"
        + DNS_NODE
        + " 'pkill -u "
        + username
        + " dnsserver'"
    )
    os.system(ssh_command)


def stop_http(username, keyfile):
    # STop httpserver to each replica server
    for node in HTTP_NODES:
        ssh_command = (
            "ssh -i "
            + keyfile
            + " "
            + username
            + "@"
            + node
            + " 'pkill -u"
            + username
            + " python3'"
        )
        os.system(ssh_command)
        print("KILLED httpserver in node:", node)

def main():
    port, origin_server, name, username, keyfile = parse_args(sys.argv[1:])
    print(port, origin_server, name, username, keyfile)

    stop_dns(username, keyfile)
    print("KILLED dnsserver")

    stop_http(username, keyfile)

main()
